import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import NavSideBar from "./_Components/NavSideBar/NavSideBar";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
				suppressHydrationWarning>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange>
					<SidebarProvider>
						<NavSideBar />
						<main className="w-full relative">
							<div className="w-full flex hello">
								<div className="w-full p-2 m-2 rounded-sm bg-gray-100 dark:bg-slate-900">
									<SidebarTrigger className="absolute top-10 left-10" />
									<Toaster
										closeButton
										position="top-center"
									/>
									{children}
								</div>
							</div>
						</main>
					</SidebarProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
